name: toc
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.01.10=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1t=h7f8727e_0
  - python=3.10.11=h7a1cb2a_2
  - readline=8.2=h5eee18b_0
  - setuptools=66.0.0=py310h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.38.4=py310h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - anyio==3.6.2
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.2.3
      - asttokens==2.2.1
      - async-timeout==4.0.2
      - attrs==23.1.0
      - backcall==0.2.0
      - backoff==2.2.1
      - beautifulsoup4==4.12.2
      - bleach==6.0.0
      - blis==0.7.9
      - catalogue==2.0.8
      - certifi==2023.5.7
      - cffi==1.15.1
      - charset-normalizer==3.1.0
      - click==8.1.3
      - cmake==3.26.3
      - comm==0.1.3
      - confection==0.0.4
      - contourpy==1.0.7
      - cycler==0.11.0
      - cymem==2.0.7
      - dataclasses-json==0.5.7
      - datasets==2.12.0
      - debugpy==1.6.7
      - decorator==5.1.1
      - defusedxml==0.7.1
      - dill==0.3.6
      - dsp-ml==0.1.5
      - executing==1.2.0
      - faiss-cpu==1.7.4
      - fastjsonschema==2.16.3
      - filelock==3.12.0
      - fonttools==4.39.4
      - fqdn==1.5.1
      - frozenlist==1.3.3
      - fsspec==2023.5.0
      - greenlet==2.0.2
      - huggingface-hub==0.14.1
      - idna==3.4
      - install==1.3.5
      - ipykernel==6.23.1
      - ipython==8.13.2
      - ipython-genutils==0.2.0
      - ipywidgets==8.0.6
      - isoduration==20.11.0
      - jedi==0.18.2
      - jinja2==3.1.2
      - joblib==1.2.0
      - jsonpointer==2.3
      - jsonschema==4.17.3
      - jupyter==1.0.0
      - jupyter-client==8.2.0
      - jupyter-console==6.6.3
      - jupyter-core==5.3.0
      - jupyter-events==0.6.3
      - jupyter-server==2.5.0
      - jupyter-server-terminals==0.4.4
      - jupyterlab-pygments==0.2.2
      - jupyterlab-widgets==3.0.7
      - kiwisolver==1.4.4
      - langchain==0.0.194
      - langchainplus-sdk==0.0.6
      - langcodes==3.3.0
      - lit==16.0.5
      - markupsafe==2.1.2
      - marshmallow==3.19.0
      - marshmallow-enum==1.5.1
      - matplotlib==3.7.1
      - matplotlib-inline==0.1.6
      - mistune==2.0.5
      - mpmath==1.3.0
      - multidict==6.0.4
      - multiprocess==0.70.14
      - murmurhash==1.0.9
      - mypy-extensions==1.0.0
      - nbclassic==1.0.0
      - nbclient==0.7.4
      - nbconvert==7.4.0
      - nbformat==5.8.0
      - nest-asyncio==1.5.6
      - networkx==3.1
      - nltk==3.8.1
      - notebook==6.5.4
      - notebook-shim==0.2.3
      - numexpr==2.8.4
      - numpy==1.24.3
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - openai==0.27.6
      - openapi-schema-pydantic==1.2.4
      - packaging==23.1
      - pandas==2.0.1
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pathy==0.10.1
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==9.5.0
      - pip==23.1.2
      - platformdirs==3.5.1
      - preshed==3.0.8
      - prometheus-client==0.16.0
      - prompt-toolkit==3.0.38
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyarrow==12.0.0
      - pycparser==2.21
      - pydantic==1.10.7
      - pygments==2.15.1
      - pyparsing==3.0.9
      - pyrsistent==0.19.3
      - python-dateutil==2.8.2
      - python-json-logger==2.0.7
      - pytz==2023.3
      - pyyaml==6.0
      - pyzmq==25.0.2
      - qtconsole==5.4.3
      - qtpy==2.3.1
      - regex==2023.5.5
      - requests==2.30.0
      - responses==0.18.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - send2trash==1.8.2
      - sentence-transformers==2.2.2
      - sentencepiece==0.1.99
      - six==1.16.0
      - smart-open==6.3.0
      - sniffio==1.3.0
      - soupsieve==2.4.1
      - spacy==3.5.3
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.4
      - sqlalchemy==2.0.15
      - srsly==2.4.6
      - stack-data==0.6.2
      - sympy==1.12
      - tenacity==8.2.2
      - terminado==0.17.1
      - thinc==8.1.10
      - threadpoolctl==3.1.0
      - tiktoken==0.4.0
      - tinycss2==1.2.1
      - tokenizers==0.13.3
      - torch==2.0.1
      - torchvision==0.15.2
      - tornado==6.3.2
      - tqdm==4.65.0
      - traitlets==5.9.0
      - transformers==4.29.2
      - triton==2.0.0
      - typer==0.7.0
      - typing-extensions==4.5.0
      - typing-inspect==0.9.0
      - tzdata==2023.3
      - ujson==5.7.0
      - uri-template==1.2.0
      - urllib3==2.0.2
      - wasabi==1.1.1
      - wcwidth==0.2.6
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.5.1
      - widgetsnbextension==4.0.7
      - wikiextractor==3.0.6
      - xxhash==3.2.0
      - yarl==1.9.2
prefix: /home/gangwoo/anaconda3/envs/dsp
